### ISSUE TITLE
Création d'opération

### ISSUE THREAD

**Issue by mencattini** [cui-unige/proofs-mencattini#1]
Hello,

J'avais deux questions qui m'empêche de bien commencer:

1) Comment fait-on pour avoir plusieurs cas pour une opération. Par exemple pour le ```Boolean.Equals```.
J'aurai tendance à écrire quelque chose comme ça:
```
Boolean [Adt.axioms].equals_true = Adt.axiom {
	Boolean.Equals {Boolean.True {}, Boolean.True {}},
	Boolean.True {}
}
```
Mais je ne couvre qu'un cas, du coup est-ce que je peux (dois?) définir un autre _cas_ avec le même nom:

```
Boolean [Adt.axioms].equals_true = Adt.axiom {
	Boolean.Equals {Boolean.False {}, Boolean.False {}},
	Boolean.True {}
}
```

2) Comment puis-je tester le fait que ```Boolean.Not``` est juste? J'ai tenté d'écrire:
```
	it ("verifing the not", function()
		assert.are.equal (Boolean.Not{Boolean.True}, Boolean.True)
	end)
```
Cependant j'ai une erreur: 
``` ./src/adt/init.lua:118: 1 must be a term or a variable ```.

Merci d'avance

**Comment by saucisson** [comment]
Pour les deux axiomes, ils doivent avoir un nom différent, sinon tu écrase le premier. 
Regarde par exemple:

```lua
-- Not
Boolean [Adt.axioms].not_true = Adt.axiom {
  Boolean.Not { Boolean.True {} },
  Boolean.False {}
}
Boolean [Adt.axioms].not_false = Adt.axiom {
  Boolean.Not { Boolean.False {} },
  Boolean.True {},
}
```

**Comment by saucisson** [comment]
Pour le `not`, tu aurais dû écrire :

```lua
        assert.are.equal (Boolean.Not{Boolean.True {}}, Boolean.True {})
```

En effet `Boolean.True` est une opération, pas un terme. Pour construire un terme, il faut lui ajouter `{}` (paramètres vides).
Mais de toute façon, ça ne testerait pas car pour appliquer un axiome, il faut utiliser les preuves. Don tu peux tester en créant un théorème à partir de l'axiome et en faisant une petite preuve.

Là tu voudrais faire de la réécriture, ce sera le prochain TP !

**Comment by mencattini** [comment]
D'accord, merci beaucoup, j'ai pu avancé.

Autre question: est-il possible d'utiliser les variables booléene comme pour les naturels?
Avec les naturels, on a : 
```
Natural._x
```
Est-ce qu'on peut faire la même chose avec les booléens : 
```
Boolean._x
```
Qui pourrait valoir true ou false.
Pour couvrir plus de cas?.

Merci d'avance

**Comment by saucisson** [comment]
Bien sûr, les variables peuvent s'utiliser avec n'importe quel sort.
