### ISSUE TITLE
Theorem.substitution

### ISSUE THREAD

**Issue by mencattini** [cui-unige/proofs-mencattini#2]
Hello,

J'essaie d'implémenter la méthode ```substitution``` de ```Theorem```.

Cependant je bloque sur un détail d'implémentation. 
Comment faire pour obtenir une table à partir d'un ```Sort```.
En effet, je pensais utiliser:
```Adt.Term.__div(myTerm, remplacement)```
Afin de remplacer la variable dans le terme, mais le type de remplacement est un ```Sort``` et je n'ai pas trouvé comment faire la conversion.

Merci d'avance

**Comment by saucisson** [comment]
Tu ne peux remplacer une variable que par une autre variable ou par un term, en aucun cas par un sort. Peux-tu me dire ce que tu veux remplacer, et pourquoi tu veux le remplacer par un sort ?

**Comment by mencattini** [comment]
Je ne savais pas comment prendre le problème, du coup je pensais utiliser
```term / mapping``` pour remplacer la variable du théorème par le nouveau mapping.
Je pensais que le paramètre ```replacement``` correspondait au nouveau mapping.
Mais vu que c'est un sort, je ne savais pas si c'était possible.
Est-ce que je suis sur la bonne voie, ou bien j'utilise totalement la mauvaise fonction?

**Comment by saucisson** [comment]
`term / mapping` remplace effectivement les variables de `term` par le `mapping`. Mais pourquoi serait-il un sort ? As-tu un exemple plus précis de ce que tu voudrais faire ?

**Comment by mencattini** [comment]
Par ce code:
```
		local t = {}
		local i = 0
		
		Fun.each(function(terms)
			t[i] = terms
			i = i + 1
		end, theorem)
```
J'obtiens les deux terms composants le théorème.

La signature de la fonction est : ``` function Theorem.substitution (theorem, variable, replacement)```

Du coup je pensais faire:
```
lhs = t[0] / replacement
rhs = t[1] / replacement
```
Pour remplacer la variable dans les deux termes et donc dans le théorème.

En affichant ``` replacement``` j'obtiens par exemple ```True : bool```. Je pensais donc pouvoir utiliser l'opérateur ``` / ```.

**Comment by saucisson** [comment]
Euh oui, ça devrait fonctionner. `True : Bool` est soit une opération, soit un terme, mais pas un sort (qui serait `Bool` tout simplement).

**Comment by mencattini** [comment]
En ayant une fonction comme cela:
```
function Theorem.substitution (theorem, variable, replacement)
  assert (getmetatable (theorem) == Theorem,
          "theorem must be a term")
  assert (getmetatable (variable) == Adt.Variable,
          "variable must be a variable")
  assert (getmetatable (replacement) == Adt.Term,
          "replacement must be a term")
  assert (variable [Adt.Sort] == replacement [Adt.Sort],
          "variable and replacement must be of the same sort")
  -- TODO: repol	local table = {}
		local t = {}
		local i = 0
		
		Fun.each(function(terms)
			t[i] = terms
			i = i + 1
		end, theorem)
		
		local var = all_variables(theorem)
		table.insert(var, replacement)

		return Theorem {
    variables = var ,
    when = when,
    [1]  = t[0]/replacement,
    [2]  = t[1]/replacement,
  }
end
```
J'ai une erreur sur le test de la substitution.
```
Error → src/adt/theorem_spec.lua @ 112
#test theorem can apply substitution
./src/adt/init.lua:214: Sort must be a variable
```

**Comment by saucisson** [comment]
Ça signifie que, dans `replacement` tu dois avoir quelque chose qui n'est pas une variable comme clé.

**Comment by mencattini** [comment]
D'accord.
Comment construit-on un mapping? (je n'ai pas trouvé dans la documentation).

**Comment by saucisson** [comment]
C'est tout simplement une table... donc par exemple:

```lua
local mapping = {}
mapping [cle] = valeur
```

**Comment by mencattini** [comment]
Comment s'utiliser le remplacement, car si je fais:
```
		local result = t[0] [Operation] (Fun.frommap (t[0])
       : filter  (function (k, _) return type (k) ~= "table" end)
       : map     (function (k, v) if v[k] == variable then
			 v[k] = replacement
			 end
		 end)
       : tomap ())
```
Où t[0] est un ```terme```, ```variable``` une variable et ```replacement``` une variable.
J'obtiens une erreure:
```
Error → src/adt/theorem_spec.lua @ 112
#test theorem can apply substitution
/usr/share/lua/5.3/fun.lua:802: table index is nil
```

**Comment by saucisson** [comment]
```lua
(Fun.frommap (t[0])
       : filter  (function (k, _) return type (k) ~= "table" end)
```
retourne un itérateur clé/valeur sur tous les sous-termes de `t [0]`.

```lua
: map     (function (k, v) if v[k] == variable then
             v[k] = replacement
             end
         end)
```
itère sur tous les sous-termes (qui sont bien `v` à chaque fois). Mais que veut dire ton `v [k]` ?
Ce que tu cherches à savoir c'est si `v` est `variable`, non ?

De plus, pourquoi fais-tu une affectation dans le `map` ? Le principe du `map` c'est de retourner la nouvelle clé/valeur de substitution.

**Comment by mencattini** [comment]
Car si je fais:
``` v[k] ``` j'obtiens les variables contenues dans le terme.

Exactement, je cherche à savoir si ```v``` est ```variable``` pour la remplacer par ```replacement```.

Du coup comment faire la substitution?

**Comment by saucisson** [comment]
Tout simplement :

```lua
return k, replacement
```

Et non, avec `v [k]` tu n'obtiens pas les variables du terme. Tu obtiens un truc, qui peut être un sous-sous-terme de `t [0]`. `v` est déjà un sous-terme, donc potentiellement une variable.
