### ISSUE TITLE
Test (couverture de code)

### ISSUE THREAD

**Issue by mencattini** [cui-unige/proofs-mencattini#5]
Hello,

J'ai essayé de faire des tests pour les ```Boolean```, mais je finis toujours par retomber sur de la réécriture.
Est-ce qu'il serait possible d'avoir une indication sur comment tester (juste un truc bête des ```Boolean```) afin d'avoir une base pour commencer?

Merci d'avance

**Comment by saucisson** [comment]
Ce que tu veux prouver, c'est quelque chose du genre :

```lua
  operation (...) = generator (...)
```

Pour cela tu as un axiome sur `operation (...)` dont la partie droite est généralement plus proche du générateur. Donc avec de la transitivité, tu devrais pouvoir faire une preuve.

**Comment by mencattini** [comment]
J'ai essayé de faire qqch comme cela:
```lua
	it ("test not",function()
		local t1 = Theorem.axiom(Boolean [Adt.axioms].not_true)
		local t2 = Theorem {
			Boolean.False{},
			Boolean.False{}
		}
		local t3 = Theorem.transitivity(t1,t2)
		assert.are.equal (t1,t3)
	end)
```
Pour utiliser la transitivité, je suis obligé d'avoir des `Theorem`. Mais ça me semble bizarre ce que j'ai fait.

**Comment by saucisson** [comment]
Bon, sur cet exemple il n'y a pas grand chose de plus à faire, en effet. Tu pourrais aussi essayer de prouver que `not (not (true)) = true` par exemple. Ou  `not (not ($x)) = $x` ?
